# Generated by Django 2.0 on 2018-05-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='stop',
            field=models.DateField(null=True),
        ),
    ]
