# Generated by Django 2.0 on 2018-05-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='stop',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
