# Generated by Django 2.0 on 2018-05-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180509_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='isavailable',
            field=models.BooleanField(default=True),
        ),
    ]
