# Generated by Django 2.0 on 2018-02-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='memo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='telephone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
