# Generated by Django 2.0 on 2018-03-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='stop',
            field=models.DateTimeField(null=True),
        ),
    ]
