# Generated by Django 2.0 on 2018-03-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180307_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
